REPL-5(tree): DnD for nesting structure.
feature-sliced/repl pull request #13
Opened 2021-12-26 17:40 UTC by Krakazybik

## Description
Добавлено:
- Ховер выделенных элементов при DnD наведении.
- Паддинг вложенных элементов от глубины.
- Перенос вложенных элементов.

## Reference:
#5

## Checklist
- [X] Description added
- [ ] Self-reviewed
- [ ] CI pass

2021-12-26 19:12 UTC, Krakazybik commented
Есть небольшие проблемы с оверлеем (то что упрыгивает в конец), а ещё оверлеевский айтем не реагирует на depth.
https://user-images.githubusercontent.com/1334019/147417802-bbcab625-dc6a-47e4-b472-3a0e4c4d6803.mp4

2021-12-26 20:39 UTC, AlexandrHoroshih commented
Да, это то, что нужно 👍

2021-12-28 10:16 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/tree.tsx
> -        <SortableContext
Отключен, т.к. требует доработки.

2021-12-29 10:02 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/tree.tsx
> -        <SortableContext
@AlexandrHoroshih вынести в отдельный issue?

2021-12-29 10:04 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/ui/tree.tsx
> -        <SortableContext
Если считаешь нужным 🤔 
А какие с ним проблемы?

В их демке вроде неплохо работает
https://5fc05e08a4a65d0021ae0bf2-unebtvimdp.chromatic.com/?path=/story/examples-tree-sortable--all-features

2021-12-29 10:05 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/ui/tree.tsx
> -        <SortableContext
На всякий случай, сорсы демки выше:
https://github.com/clauderic/dnd-kit/tree/master/stories/3%20-%20Examples/Tree

2021-12-29 10:07 UTC, Krakazybik commented
Пока вот такая штука, есть ещё кейсы с некорректным вычеслением глубины потомков. Как будет посвободнее времени, поправлю. 

https://user-images.githubusercontent.com/1334019/147650893-6ba2f24e-c8f6-494b-be4b-adc1c96b3f4a.mp4

2021-12-29 10:13 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/tree.tsx
> -        <SortableContext
> Если считаешь нужным thinking А какие с ним проблемы?
> 
> В их демке вроде неплохо работает https://5fc05e08a4a65d0021ae0bf2-unebtvimdp.chromatic.com/?path=/story/examples-tree-sortable--all-features

На первом видео видно как уползают hovered айтемы в совсем неожиданные места. 
Момент 0.03-0.05

2022-01-01 18:41 UTC, Krakazybik commented
Current progress:

https://user-images.githubusercontent.com/1334019/147857813-df91c7ba-c736-49f2-a4ee-f748c2e2b921.mp4

2022-01-01 18:53 UTC, Krakazybik reviewed
Ховер выделенных элементов при DnD наведении.
Паддинг вложенных элементов от глубины.
Перенос вложенных элементов.
Перемещение в ROOT при перетаскивании за границы.

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/config/theme.ts
Конфигурация величины отступа нод нашего дерева в зависимотси от глубины, а также настройки выделения целевой ноды при перетаскивании.

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/lib.ts
> +
Рекурсивная модификация глубины вложенности для дочерних нод.

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/lib.ts
> +}
Если утаскиваем за границу, определяемую в isOutOfBounds, перемещаем ноду в ROOT. 
[thought:](https://conventionalcomments.org/#labels) М.б вынести данные значения в конфиг темы?

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/mockData.ts
> +
Мокнуты данные, для более удобной разработки и возможно тестирования

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/state.ts
Соответсвенно в DEV режиме используем мокнутое дерево.

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/state.ts
> +
При перетаскивании ноды, сворачиваем её.

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/state.ts
> +  })
Если утаскиваем ноду за границы, перемещаем ноду в ROOT.

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/state.ts
>    });
Если под нами есть какая-либо нода в момент отпускания кнопки мыши при перетаскивании - становимся её потомком.

2022-01-01 18:53 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/state.ts
> +  })
Подсвечиваем ноды, когда перемещаемся над ними.

2022-01-01 18:57 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/tree.tsx
> -        <SortableContext
Вынесено в #14

2022-01-04 10:22 UTC, AlexandrHoroshih requested changes
@Krakazybik 
Привет! Я тут наконец добрался до твоего ПР: всё круто, но есть пара моментов, которые меня смущают - о них отписал

2022-01-04 10:22 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/model/lib.ts
> +}
**suggestion**: Аналогично, на мой взгляд, подобные лимиты относятся к настройкам самой библиотеки 🤔 
Предлагаю также занести в настройки через пропсы
```ts
type StructTreeProps = {
  tree: ITreeState;
  ...
  limitX?: number;
  limitY?: number;
};
```
Альтернативно, эти лимиты могут быть в настройках фабрики модели 🤔 
```ts
createTreeState({
 limitX: ...
})
```

2022-01-04 10:22 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/model/state.ts
**suggestion(non-blocking)**: Как насчет, вместо подобных временных решений, добавить фичу сохранения текущего варианта в localStorage? Это будет полезно, чтобы не потерять свой набросок, если вдруг забыл сохранить его

На этом этапе можно сделать просто через [effector-storage](https://github.com/yumauri/effector-storage)
```ts
import { persist } from "effector-storage/local"

...

persist({
 store: $tree,
 key: "draft-tree"
})
```

2022-01-12 08:30 UTC, Krakazybik commented on src/shared/config/theme.ts
> +export const hoveredNodeBorderStyle = "2px solid #f81ce5";
@AlexandrHoroshih а почемы именно через пропсы? Такое чувство что там по глубине уйдёт очень далеко.

Может быть сделать ThemeContext вроде 

```js


type TreeTheme = {
  depthPadding: number;
  style: {
    hoveredNode: React.CSSProperties;
  };
  hoveredNodeClassName?: string;
}

const treeThemeContextDefault = {
  depthPadding: 30,
  style: {
    hoveredNode: {
      border: "2px solid #f81ce5"
    },
  }
}

const TreeThemeContext = createContext<TreeTheme>(treeThemeContextDefault);
```

и в последствии заворачивать в этот стайл, всё что связано со стилем дерева

2022-01-12 08:40 UTC, AlexandrHoroshih commented on src/shared/config/theme.ts
> +export const hoveredNodeBorderStyle = "2px solid #f81ce5";
Внутри самого компонента библиотеки можно прокидывать как угодно и через контекст тоже (это даже лучший вариант будет), я именно о возможности настраивать вид компонента общепринятым в реакте способом конфигурации (ну, через пропсы т.е.)

Соответственно, можно сделать внутри контекст, как ты предложил + дать возможность оверрайдить его дефолтные настройки пропсами компонента
Так получим возможность конфигрурировать отображение чисто через публичное апи на пропсах и не залезая в кишки каждый раз

2022-01-13 12:03 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/index.tsx
> +  style?: Record<string, React.CSSProperties>;
Что-то сейчас смотрю и кажется очень спорным...

2022-01-13 12:05 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/ui/index.tsx
> +  style?: Record<string, React.CSSProperties>;
Детально я попозже смогу посмотреть, но здесь точно не стоит в style кидать что-то кроме собственно реактовского объекта style - т.к. это, можно сказать, повсеместная конвенция, лучше, например, выбрать другое имя этому пропу

2022-01-13 12:09 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/index.tsx
> +  style?: Record<string, React.CSSProperties>;
согласен

2022-01-14 20:01 UTC, AlexandrHoroshih requested changes

2022-01-14 20:25 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/state.ts
> +export const createTreeState = (limitX = -200, limitY = -30) => {
Да, влево. На самом деле мне это решение с настройкой не очень то нравится и вообще не нравится данная реализация границ перетаскивания. Т.е. какой у нас кейс вылезает(вообще для чего нам эти границы), мы можем не хотеть вытащить элемент из родителя, а просто сбросить его на место, данный лимит регулирует это. Т.е. на данный момент работает только перетаскивание влево и вверх насколько я помню. Т.к. нам надо вычислять размера самого блока ещё. И я хотел подумать над реализией в рамках отдельного PR, а это решение оставить как временное, т.к. отсутсвие какого-либо решения либо постоянно вытаскивает из родителя, либо не вытаскивает на верхний уровень вообще =) Какие идеи по этому поводу? Может регулировать это отдельным блоком и отслеживать утаскивание за его зону, и настраивать на уровне UI с помощью margin?

2022-01-14 20:31 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/model/state.ts
> +export const createTreeState = (limitX = -200, limitY = -30) => {
https://user-images.githubusercontent.com/1334019/149581113-16760bcb-16a4-4b02-a8b3-f6ed4d5644b9.mp4

с видео понятнее будет надеюсь)

2022-01-14 20:50 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/model/state.ts
> +export const createTreeState = (limitX = -200, limitY = -30) => {
> я хотел подумать над реализией в рамках отдельного PR, а это решение оставить как временное
Окес, давай так 👍

2022-01-14 20:52 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/model/state.ts
> +export const createTreeState = (limitX = -200, limitY = -30) => {
> Какие идеи по этому поводу?

Постараюсь потыкать на днях, мб что и придумаю 🤔

2022-01-15 16:59 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/index.tsx
> +  style?: Record<string, React.CSSProperties>;
@AlexandrHoroshih что-то я нормальное название придумать не могу :rofl: мб `appearance` ?

2022-01-15 18:19 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/ui/index.tsx
> +  style?: Record<string, React.CSSProperties>;
Как насчет не прокидывать объект? Свойство style я бы всё равно оставил, но вляить оно должно на корневую ноду компонента.
Остальные специальные стили можно добавить как `hoveredNodeStyle` и etc + опционально, парные className свойства к ним 🤔

2022-01-15 18:51 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/index.tsx
> +  style?: Record<string, React.CSSProperties>;
В принципе можно и не как объект, просто такое ощущение, что потом количество пропсов в итоге будет приличным. Давай, а там уже если и правда их будет неприлично много, то уже будем думать )

2022-01-18 20:33 UTC, AlexandrHoroshih requested changes

2022-01-18 20:33 UTC, AlexandrHoroshih commented on src/shared/lib/react-effector-struct-tree/ui/index.tsx
> +      <StructTreeBase style={style}/>
**issue**: 
Кажется, типы не сходятся 🤔
`StructTree` имеет `style?: Record<string, React.CSSProperties>;`, а `StructTreeBase`, куда этот style пролетает, ` style?: React.CSSProperties` 
Или я что-то упускаю? 🤔

2022-01-18 20:46 UTC, Krakazybik commented on src/shared/lib/react-effector-struct-tree/ui/index.tsx
> +      <StructTreeBase style={style}/>
Хм. А почему TS не матюгнулся даже? Как он типы привёл то?

2022-01-20 09:57 UTC, azinit commented
Вы шо, психи 😄 

![image](https://user-images.githubusercontent.com/42924400/150316088-12bfebc2-7314-4063-ad9f-e40dcf2957ca.png)

2022-01-20 10:00 UTC, AlexandrHoroshih commented
Непосредственных изменений немного 🤔 

Вообще, уже все вопросы закрыты и основная задача базово сделана

2022-01-20 10:01 UTC, AlexandrHoroshih approved these changes

2022-01-20 10:01 UTC, merged